(define (domain office)
    (:requirements :strips :typing)
    (:predicates (power ?p) 
	             (sensor ?s) 
				 (free ?a)  
				 (actuator ?a)
				 (nouserpresent ?np)
				 (userpresent ?up)
	)
    (:action controlling
          :parameters (?a ?s)
           :precondition(and (actuator ?a) 
                        (free ?a) 
                        (not(power ?a))
                        (not(userpresent ?s))
                        (nouserpresent ?s)
                        
						)
           :effect  (and (power ?s) 
                    (not (free ?a))
                    (not (nouserpresent ?s))
                    (userpresent ?s)
                    )
    )
    (:action aftercontrolling
           :parameters (?a ?s)
           :precondition (and (not(free ?a)) (power ?a))
           :effect (free ?a)
	)
)
